name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Puedes usar una versión más reciente si lo deseas

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge
        run: surge --project ./ --domain your-custom-domain.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
